# Generated by Django 5.0.6 on 2024-08-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_content',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.TextField(),
        ),
    ]
